sudo: required

language: php

services:
  - docker

before_install:
  - sudo service mysql stop
  - docker-compose up --build -d

script:
  - docker exec -it php bin/phpunit

after_script:
  - docker-compose down