sudo: required

services:
  - docker

before_install:
  - sudo service mysql stop
  - docker-compose up --build -d
  - docker exec security_comparator_apache composer install
  - docker exec security_comparator_apache npm install
  - docker exec security_comparator_apache bin/console doctrine:database:create
  - docker exec security_comparator_apache bin/console doctrine:schema:create
  - docker exec security_comparator_apache bin/console doctrine:fixtures:load

script:
  - docker exec security_comparator_apache bin/phpunit