sudo: required

language: php

services:
  - docker

before_install:
  - sudo service mysql stop
  - docker-compose up --build -d
  - docker exec lmu2fsymfony_apache composer install
  - docker exec lmu2fsymfony_apache npm install
  - docker exec lmu2fsymfony_apache bin/console doctrine:database:create
  - docker exec lmu2fsymfony_apache bin/console doctrine:schema:create
  - docker exec lmu2fsymfony_apache bin/console doctrine:fixtures:load

script:
  - docker exec lmu2fsymfony_apache bin/phpunit

after_script:
  - docker-compose down