sudo: required

language: php

services:
  - docker

before_install:
  - sudo service mysql stop
  - docker-compose up --build -d
  - docker exec lmu2fsymfony_apache composer install
  - docker exec lmu2fsymfony_apache npm install

script:
  - docker exec lmu2fsymfony_apache bin/phpunit

after_script:
  - docker-compose down