version: '3.1'
services:
  apache:
    build: docker-apache
    container_name: lmu2fsymfony_apache
    image: lmu2fsymfony_apache
    links:
      - mariadb
    ports:
      - 443:443
    restart: always
    volumes:
      - ./symfony/:/var/www/html/
    networks:
      app_net:
        ipv4_address: 172.16.238.10
  mariadb:
    container_name: lmu2fsymfony_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=Je suis un boulet !
    image: mariadb:10.2.11
    ports:
      - 3306:3306
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.9
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24