framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    csrf_protection: true
    #http_method_override: true
    #trusted_hosts: ~
    # uncomment this entire section to enable sessions
    session: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true