security:
    encoders:
        App\Entity\Member:
            algorithm: bcrypt
    providers:
        our_db_provider:
            entity:
                class: App\Entity\Member
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: our_db_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator