security:
    encoders:
        App\Entity\Member:
            algorithm: bcrypt
    providers:
        our_db_provider:
            entity:
                class: App\Entity\Member
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: our_db_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                    - App\Security\MemoryAuthenticator
                    - App\Security\LogoutFormAuthenticator
                entry_point: App\Security\LoginFormAuthenticator
    access_control:
        -
            path: ^/(logout|view-my-u2f-tokens|add-u2f-token|delete-u2f-token/[0-9]+|edit-u2f-token/[0-9]+)
            roles: ROLE_USER
        -
            path: ^/login
            allow_if: "not has_role('ROLE_USER')"