security:
    encoders:
        App\Entity\Member:
            algorithm: bcrypt
    providers:
        our_db_provider:
            entity:
                class: App\Entity\Member
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: our_db_provider
            logout:
                path: /authenticated/logout
            guard:
                authenticators:
                    - App\Security\MemberAuthenticator
            access_denied_handler: App\Security\AccessDeniedHandler
    access_control:
        -
            path: ^/admin(/.*)?$
            roles: ROLE_ADMIN
        -
            path: ^/authenticated/.*$
            roles: ROLE_USER
        -
            path: ^/not-authenticated/.*$
            allow_if: "not has_role('ROLE_USER')"
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER